version: "3.8"

services:
  server:
    image: 'nginx:stable-alpine'
    ports:
      - '8000:80'
    volumes:
      - .:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql

  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - .:/var/www/html:delegated

  mysql:
    image: mysql:5.7
    platform: linux/x86_64
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: forever_note
      MYSQL_USER: forever_note
      MYSQL_PASSWORD: secret
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysql-data:/var/lib/mysql

  composer:
    image: composer:latest
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: [ "composer" ]

  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - .:/var/www/html
    entrypoint: [ "php", "/var/www/html/artisan" ]
    depends_on:
      - php
      - mysql

  npm:
    build:
      context: .
      dockerfile: ./dockerfiles/npm.dockerfile
    working_dir: /var/www/html/client
    ports:
      - '3000:3000'
    entrypoint: [ "npm" ]
    volumes:
      - ./client:/var/www/html/client

volumes:
  mysql-data:
